spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://54.180.119.91:3306/sakila?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: test
    password: 123456